[workspace]
members = [

    # Core library components to create & parse vaults
    "lockchain-core",
    "lockchain-core/lockchain-files",
    "lockchain-core/lockchain-crypto",

    # Primary data server
    "lockchain-server",

    # RESTful API layer
    "lockchain-http",
]