[package]
name = "lockchain-crypto"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
lockchain-core = { path = "../lockchain-core" }
serde_derive = "1.0"
serde = "1.0"

miscreant = "0.3"
base64 = "0.8"
rand = "*"
blake2 = "*"