[package]
name = "lockchain-core"
description = "Provides common abstractions for the lockchain crate ecoystem"
docs = "https://docs.rs/lockchain-core"
website = "https://github.com/spacekookie/lockchain/tree/master/lockchain-core"
readme = "README.md"
license = "MIT/X11 OR Apache-2.0"
version = "0.3.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde_derive = "1.0"
serde = "1.0"